development:
  adapter: async
  allowed_request_origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://127.0.0.1:3000
    - http://127.0.0.1:3001


test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: ubiquitous_screens_production
